name: text_scanner
version: 1.0.0+1
publish_to: none
description: A new Flutter project.
environment: 
  sdk: '>=2.12.0 <3.0.0'

dependencies: 
  cupertino_icons: ^1.0.2
  google_ml_kit: 0.7.3
  image_cropper: 1.4.1
  image_picker: 0.8.4+4
  path_provider: 2.0.7
  permission_handler: 8.3.0
  flutter: 
    sdk: flutter

dev_dependencies: 
  flutter_lints: ^1.0.0
  flutter_test: 
    sdk: flutter

flutter: 
  uses-material-design: true

